/*
Magnitude Analysis
*/

USE [DataWarehouseAnalytics];
GO
-- total customers by countries
select count(distinct customer_id) as total_customers_by_country ,country
from gold.dim_customers
group by country 
order by total_customers_by_country desc
-- total customers by gender
select count(distinct customer_id) as total_customers_by_gender ,gender
from gold.dim_customers
group by gender 

-- total products by category
select count(product_id) as total_customers_by_category ,category
from gold.dim_products
group by category 
having category is not null
-- average costs in each category?
select avg(cost) as avg_category_costs ,category
from gold.dim_products
group by category 
having category is not null
order by avg_category_costs desc
-- total revenue generated for each category?
select sum(sales_amount) as total_category_revenue , category as category_name
from gold.dim_products p join gold.fact_sales s  on p.product_key=s.product_key
group by category
order by total_category_revenue desc


-- total revenue generated by each customer?
select first_name+' '+last_name as customer_name 
       ,sum(sales_amount)as total_revenue
       from gold.fact_sales s join gold.dim_customers c
       on s.customer_key = c.customer_key 
       group by first_name ,last_name 
       order by total_revenue desc


-- distribution of sold items across countries?
select sum(s.sales_amount) ,p.product_name ,c.country
from gold.dim_products p  join gold.fact_sales s on p.product_key =s.product_key
 join gold.dim_customers c on s.customer_key =c.customer_key 
group by p.product_name,c.country
order by c.country desc

